### ISSUE TITLE
Set up the test pipeline for this project.

### ISSUE THREAD

**Issue by wammar** [higgood/med-jargon-explain-inator#16]

**Comment by zepam** [comment]
05/16: Yes, it would be nice to have CI/CD for this project, but I recommend we don't because:
* we have a limited amount of time and this would take too much time to set up
* we haven't released anything into production and we don't need to continually test new updates to make sure it works on all platforms
* would be more efficient to set up regression testing and only use that for now

**Comment by zepam** [comment]
change 5/16:
working on a big CI/CD pipeline is out of scope for this project. It will be turned into developing a test pipeline instead.

**Comment by wammar** [comment]
Deprioritizing the testing framework.
